// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0YUXcklOhTAFyKbwMxFnInvf3A9N_zLI',
    appId: '1:98427392399:web:45984e7c2b763ad1efbbfa',
    messagingSenderId: '98427392399',
    projectId: 'courseplatform-b0cfa',
    authDomain: 'courseplatform-b0cfa.firebaseapp.com',
    storageBucket: 'courseplatform-b0cfa.appspot.com',
    measurementId: 'G-YQ0D7N3ESF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicR39odh5idBxAebwDbhBYSF5iPfEiBs',
    appId: '1:98427392399:android:be1219828c4956a6efbbfa',
    messagingSenderId: '98427392399',
    projectId: 'courseplatform-b0cfa',
    storageBucket: 'courseplatform-b0cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8CLCzcGI7VgI3pcs311PxayQJX6uPIjA',
    appId: '1:98427392399:ios:d98ed6106487543eefbbfa',
    messagingSenderId: '98427392399',
    projectId: 'courseplatform-b0cfa',
    storageBucket: 'courseplatform-b0cfa.appspot.com',
    iosBundleId: 'com.example.mycourseplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8CLCzcGI7VgI3pcs311PxayQJX6uPIjA',
    appId: '1:98427392399:ios:d98ed6106487543eefbbfa',
    messagingSenderId: '98427392399',
    projectId: 'courseplatform-b0cfa',
    storageBucket: 'courseplatform-b0cfa.appspot.com',
    iosBundleId: 'com.example.mycourseplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0YUXcklOhTAFyKbwMxFnInvf3A9N_zLI',
    appId: '1:98427392399:web:12e27e76ab87a337efbbfa',
    messagingSenderId: '98427392399',
    projectId: 'courseplatform-b0cfa',
    authDomain: 'courseplatform-b0cfa.firebaseapp.com',
    storageBucket: 'courseplatform-b0cfa.appspot.com',
    measurementId: 'G-E8YY6H2RXP',
  );
}
